### PR TITLE
Lang dropdown

### PR DESCRIPTION
**Pull request by tony1759**
Screenshot 2024-11-08 at 5 22 50 PM

image

## Describe your changes
- Added language selector dropdown to navbar
- Implemented language persistence using localStorage
- Added i18next integration for language switching
- Updated navbar styling to match design
- Added mobile responsiveness for language selector
- About comes first in the header

## Issue ticket number and link
#30 

## Does your code meet the acceptance criteria?
- [x] Language selector shows current language
- [x] Language selection persists after page reload
- [x] Styling matches design spec
- [x] Works on mobile devices
- [x] Proper integration with i18next

## Testing done and screenshots (if relevant)
- Tested language switching functionality
- Verified persistence across page reloads
- Tested mobile responsiveness
- Verified dropdown styling and interactions

## Other comments
- Language codes are configured in `langMapping` object
- Uses Lucide React for globe icon
- Mobile menu includes language selector in hamburger menu

### CODE REVIEW

**Review by myix765 — CHANGES_REQUESTED** [review]
Nice job with changing the language! One thing is that with the dropdown, we want to have an all-purpose dropdown rather than just a dropdown for just language. This is why in the previous Dropdown component they pass in a children prop, so that the dropdown links can be anything as required. Please split this dropdown into a general purpose dropdown component, then use that dropdown to implement the language dropdown component. Since the dropdown is general purpose, the prop names should also be more general. Let me know if you have any questions!

**Review by myix765 — CHANGES_REQUESTED** [review]
Hi, thanks for separating the dropdown into a general dropdown and a language dropdown! Right now, the navbar isn't using the language dropdown though. For mobile it's still using the general dropdown and for desktop it's using other dropdown code. Please change it to use the language dropdown component. Also, please move the logic for setting and getting the language to be in the dropdown component not in Navbar, that way we can reuse the component elsewhere and it will also work.

**Comment by tony1759** [comment]
i understand it now

**Review by myix765 — APPROVED** [review]

**Review by myix765 — APPROVED** [review]
Nice job implementing the language dropdown, and thanks for making the requested changes! I tweaked the code a little to detect the language using the i18next-browser-languagedetector library so that we can detect the language from other sources, not just localstorage, but otherwise great work working with a new library!

**Pull request merged**
